name: Lint and test on pull-requests

on:
  pull_request:

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci --unsafe-perm
    - name: Test eslint
      run: npm run test:eslint
    - name: Transpile TypeScript files
      run: npm run build
    - name: Run unit tests
      run: npm run test:unit:coverage
